In [ ]:
import numpy as np

In [9]:
# interesing (error)

arr=np.arange(10)
arr1=arr[:5]

print(arr)
print(arr1)
arr1[:]=999
print(arr)
print(arr1)

# thus arr1 is a link to part of arr

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[999 999 999 999 999   5   6   7   8   9]
[999 999 999 999 999]


In [10]:
# we can do this way
arr=np.arange(10)
arr1=arr[:5].copy()

print(arr)
print(arr1)
arr1[:]=999
print(arr)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[999 999 999 999 999]
